### ISSUE TITLE
crashes in play_cast: TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by hobbes** [muammar/mkchromecast#346]
Hello, 

I get a consistent crash when I try to use mkchromecast. Here's the output with --debug:

<pre>
hobbes@sphax:~/devel/mkchromecast/mkchromecast$ bin/mkchromecast --debug
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
ALSA device name: None.
Google Cast name: None.
backends:  ['ffmpeg', 'avconv', 'parec', 'gstreamer']
USER =hobbes
PATH =/usr/local/sbin:/usr/sbin:/sbin:~/bin:/home/hobbes/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/opt/mssql-tools/bin
Mkchromecast v0.3.9
Creating Pulseaudio Sink...
Open Pavucontrol and Select the Mkchromecast Sink.
Starting Local Streaming Server
[Done]
:::audio::: chunk_size, frame_size, buffer_size: 64, 2048, 8192
Selected backend: parec
Selected audio codec: mp3
Default bitrate used: 192k
Default sample rate used: 44100Hz.
:::audio::: command ['lame', '-b', '192', '-r', '-']
 * Serving Flask app "mkchromecast.audio" (lazy loading)
PID of main process: 22424
 * Environment: production
PID of streaming process: 22430
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://192.168.5.176:5000/ (Press CTRL+C to quit)
self.cclist [[0, 'VSSLA1', 'Gcast']]
if len(self.cclist) != 0 and self.select_device == False:
 
List of Devices Available in Network:
-------------------------------------

Index   Types   Friendly Name 
=====   =====   ============= 
0 	Gcast 	VSSLA1
 
Casting to first device shown above!
Select devices by using the -s flag.
 
VSSLA1
 
def get_devices(self):
def play_cast(self):
Traceback (most recent call last):
  File "/home/hobbes/devel/mkchromecast/mkchromecast/bin/../mkchromecast/cast.py", line 309, in play_cast
    colors.options("The IP of ")
TypeError: can only concatenate str (not "NoneType") to str

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hobbes/devel/mkchromecast/mkchromecast/bin/mkchromecast", line 311, in <module>
    mk()
  File "/home/hobbes/devel/mkchromecast/mkchromecast/bin/mkchromecast", line 59, in __init__
    self.audio_linux()
  File "/home/hobbes/devel/mkchromecast/mkchromecast/bin/mkchromecast", line 80, in audio_linux
    self.cc.play_cast()
  File "/home/hobbes/devel/mkchromecast/mkchromecast/bin/../mkchromecast/cast.py", line 318, in play_cast
    + colors.success(self.cast_to.player_name)
AttributeError: 'str' object has no attribute 'player_name'
</pre>

After a bit of searching, I found the culprit at line 313 in cast.py: self.cast.socket_client.host is None. 

I then went in get_devices, and added a print(self.cast) at line 259, which returns:

Chromecast(None, port=8009, device=DeviceStatus(friendly_name='VSSLA1', model_name='VSSL A1', manufacturer='Google Inc.', uuid=UUID('1db20910-9edf-97dc-b4a9-53db76fa7f77'), cast_type='cast'))

I guess that that first None is the problem, but this being my very first experience with google casting, I'll let you get in the details :-)

System is debian sid, same problem with packaged mkchromecast or if I take it from github, the device I'm trying to connect to is a VSSL A.1

Don't hesitate to ask for more information, I'm not a developper but I'm willing to help.

Thanks,

Rémi

**Comment by heinrich-opgenoorth** [comment]
Same problem here. Turns out after upgrading "pychromecast" from 7.1.1-1 to 7.7.1-1 everythin works again. Maybe that's the case for you, too?
Now I need to find out why debian sid wants to downgrade to 7.1.1 again...

**Comment by hobbes** [comment]
indeed, I see that pychromecast has been updated to 7.7.1, and mkchromecast now works. I'm closing this issue. Thanks
