### ISSUE TITLE
AttributeError: 'module' object has no attribute 'unique'

### ISSUE THREAD

**Issue by bogdanr** [muammar/mkchromecast#154]
I just installed from git mkchromecast.
I have zeroconf 0.20.0 and I get this error:

```
Traceback (most recent call last):
  File "mkchromecast.py", line 8, in <module>
    from mkchromecast.cast import *
  File "/root/mkchromecast/mkchromecast/cast.py", line 13, in <module>
    import pychromecast
  File "/usr/lib64/python2.7/site-packages/pychromecast/__init__.py", line 15, in <module>
    from .discovery import discover_chromecasts, start_discovery, stop_discovery
  File "/usr/lib64/python2.7/site-packages/pychromecast/discovery.py", line 5, in <module>
    from zeroconf import ServiceBrowser, Zeroconf
  File "/usr/lib64/python2.7/site-packages/zeroconf.py", line 152, in <module>
    @enum.unique
AttributeError: 'module' object has no attribute 'unique'
```

**Comment by muammar** [comment]
I also have the same version and it is not creating that problem for me:

````
± % python3 mkchromecast.py                                                                                                                                                                                                            !10076
Mkchromecast v0.3.9
Selected backend: node
Default bitrate used: 192k.
Default sample rate used: 44100Hz.
PID of main process: 41211
PID of streaming process: 41214
streaming at http://10.9.118.219:5000/stream
No devices found!
Cleaning up /tmp/...
[Done]
[1]    41211 killed     python3 mkchromecast.py

>>> import zeroconf
>>> zeroconf.__version__
'0.20.0'
>>>
```

**Comment by bogdanr** [comment]
It also works for me with python3. As you can see, earlier I was testing with Python 2.7 but documentation mentions that it should also work with 2.7.

**Comment by muammar** [comment]
> It also works for me with python3. As you can see, earlier I was testing with Python 2.7 but documentation mentions that it should also work with 2.7.

I overlooked the traceback you posted. Yes, you are right, it is not working for me either. Can you tell me which version of pychromecast are you using?

**Comment by muammar** [comment]
Oh. I have seen this: https://github.com/balloob/pychromecast. Pychromecast has dropped Python2 support. So will I.
